### PR TITLE
Fix `I64_MAX_LEN`: Set it to `21`

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
I believe this is correct as written.

**Comment by NobodyXu** [comment]
@dtolnay No offense, but can you please explain why it is correct for `i64` as I have no clue why its max size is the same as `u64`?

Evaluating `len(str(-(2 ** 64 - 1)))` gives me `21` in `python3`./

**Comment by dtolnay** [comment]
i64::MIN and u64::MAX are both 20 characters. i64::MAX is 19 characters.

**Comment by NobodyXu** [comment]
> i64::MIN and u64::MAX are both 20 characters. i64::MAX is 19 characters.

Thanks, I must have made some mistake calculating the max len.

**Pull request closed without merging**
